#!/usr/bin/env bash

source "${SCRIPT_DIR}/lib/colors"

readonly passwd_file="/etc/passwd"

check_non_system_users() {
	echo -e "\n${Green}[X] Checking malicious users on ${passwd_file} file....${Reset}"
	echo -e "${Green}[X] Printing non-system users from ${passwd_file} (Username, UID, Shell)\n${Reset}"

	result=$(awk -F: '$3 > 1000 && $7 != "/usr/bin/nologin" {
        printf "[NON-SYSTEM USER] %-15s UID=%-5s SHELL=%s\n", $1, $3, $7
    }' "$passwd_file")

	if [[ -n "${result}" ]]; then
		echo "${result}"
		echo -e "\n${Yellow}[!] Review the above users carefully. Remove any unknown or unauthorized accounts.${Reset}"
	else
		echo -e "${Green}[✓] No suspicious non-system users found.${Reset}"
	fi
}
check_non_system_users

check_uid_zero_accounts() {
	echo -e "\n${Green}[X] Checking for UID 0 accounts...${Reset}"

	uid0_count=$(awk -F: '$3 == 0 {c++} END {print c+0}' "$passwd_file")

	if [[ "${uid0_count}" == 0 ]]; then
		echo -e "${Red}[CRITICAL] No UID 0 account found! System may be broken.${Reset}"
		return
	fi

	if [[ "${uid0_count}" -gt 1 ]]; then
		echo -e "${Yellow}[WARNING] Multiple UID 0 accounts detected (${uid0_count})${Reset}"
		awk -F: '$3 == 0 {print " - " $1}' "$passwd_file"
	fi

	non_root_uid0=$(awk -F: '$3 == 0 && $1 != "root" {found=1} END {print found+0}' "$passwd_file")

	if [[ "${non_root_uid0}" -eq 1 ]]; then
		awk -F: -v RED="$Red" -v RESET="$Reset" '

        $3 == 0 && $1 != "root" {
            print RED "[CRITICAL] Non-root account with UID 0: " RESET $1
        }
        ' "$passwd_file"
	else
		echo -e "[SECURE] Only root has UID 0. No issues found."
	fi
}
check_uid_zero_accounts

check_passwd_permission() {
	local permission
	permission=$(stat -c "%a" "${passwd_file}")

	echo -e "\n${Green}[X] Checking ${passwd_file} file permissions....${Reset}"

	if [[ ${permission} == 644 ]]; then
		echo -e "[✓] ${passwd_file} file permission is secure default (${permission}). No issue found."
	else
		echo -e "${Yellow}[WARN] ${passwd_file} file permissions appear to be tampered with (${permission})${Reset}"
		echo -e "${Red}[CRITICAL] Immediate attention required!${Reset}"

		if [[ ${FIX_MODE} == true ]]; then

			chmod 644 ${passwd_file}
			permission=$(stat -c "%a" "${passwd_file}")

			echo -e "\n[FIXED] ${passwd_file} file permission set to default (${permission})"
		fi
	fi
}
check_passwd_permission

check_passwd_ownership() {
	local passwd_owner
	passwd_owner=$(stat -c "%U" "${passwd_file}")

	local passwd_group
	passwd_group=$(stat -c "%G" "${passwd_file}")

	echo -e "\n${Green}[X] Checking ${passwd_file} file ownership....${Reset}"

	if [[ ${passwd_owner} && ${passwd_group} == root ]]; then
		echo -e "[✓] ${passwd_file} file is secure default (${passwd_owner}:${passwd_group}). No issue found."

		echo "-------------------------------------------------------------------------"
	else
		echo -e "${Yellow}[WARN] Someone messed with the ${passwd_file} file ownership (${passwd_owner})${Reset}"
		echo -e "${Red}[CRITICAL] Immediate attention required!${Reset}"

		if [[ ${FIX_MODE} == true ]]; then

			chown root:root ${passwd_file}
			passwd_owner=$(stat -c "%U" "${passwd_file}")
			echo -e "\n[FIXED] ${passwd_file} file ownership set to default (${passwd_owner})"

			echo "-------------------------------------------------------------------------"
		fi
	fi
}
check_passwd_ownership

if ! (return 2>/dev/null); then

	check_non_system_users
	check_passwd_permission
	check_passwd_ownership

fi
