#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/colors"

check_passwd_permission() {
	local passwd_file="/etc/passwd"

	local permission
	permission=$(stat -c "%a" "${passwd_file}")

	echo -e "${Green}[X] Checking ${passwd_file} file permissions....${Reset}"

	if [[ ${permission} == 644 ]]; then
		echo -e "\n[✓] ${passwd_file} file permission is secure default (${permission})"
	else
		echo -e "${Yellow}[WARN] ${passwd_file} file permissions appear to be tampered with (${permission})${Reset}"
		echo -e "${Red}[CRITICAL] Immediate attention required!${Reset}"

		if [[ ${FIX_MODE} == true ]]; then

			chmod 644 ${passwd_file}
			permission=$(stat -c "%a" "${passwd_file}")

			echo -e "\n[FIXED] ${passwd_file} file permission set to default (${permission})"
		fi
	fi
	echo "-------------------------------------------------------------------------"
}
check_passwd_permission

check_passwd_ownership() {
	local passwd_file="/etc/passwd"

	local passwd_owner
	passwd_owner=$(stat -c "%U" "${passwd_file}")

	local passwd_group
	passwd_group=$(stat -c "%G" "${passwd_file}")

	echo -e "\n${Green}[X] Checking ${passwd_file} file ownership....${Reset}"

	if [[ ${passwd_owner} && ${passwd_group} == root ]]; then
		echo -e "\n[✓] ${passwd_file} file is secure default (${passwd_owner}:${passwd_group})"
	else
		echo -e "${Yellow}[WARN] Someone messed with the ${passwd_file} file ownership (${passwd_owner})${Reset}"
		echo -e "${Red}[CRITICAL] Immediate attention required!${Reset}"

		if [[ ${FIX_MODE} == true ]]; then

			chown root:root ${passwd_file}
			passwd_owner=$(stat -c "%U" "${passwd_file}")

			echo -e "\n[FIXED] ${passwd_file} file ownership set to default (${passwd_owner})"
		fi
	fi
}
check_passwd_ownership
