#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/colors"

check_shadow_permission() {
	local shadow_file="/etc/shadow"

	local permission
	permission=$(stat -c "%a" "${shadow_file}")

	echo -e "${Green}[X] Checking ${shadow_file} file permissions....${Reset}"

	if [[ ${permission} == 600 ]]; then
		echo -e "\n[✓] ${shadow_file} file permission is secure default (${permission})"
	else
		echo -e "${Yellow}[WARN] ${shadow_file} file permissions appear to be tampered with (${permission})${Reset}"
		echo -e "${Red}[CRITICAL] Immediate attention required!${Reset}"

		if [[ ${FIX_MODE} == true ]]; then

			chmod 600 ${shadow_file}
			permission=$(stat -c "%a" "${shadow_file}")

			echo -e "\n[FIXED] ${shadow_file} file permission set to default (${permission})"
		fi
	fi
	echo "-------------------------------------------------------------------------"
}
check_shadow_permission

check_shadow_ownership() {
	local shadow_file="/etc/shadow"

	local shadow_owner
	shadow_owner=$(stat -c "%U" "${shadow_file}")

	local shadow_group
	shadow_group=$(stat -c "%G" "${shadow_file}")

	echo -e "\n${Green}[X] Checking ${shadow_file} file ownership....${Reset}"

	if [[ ${shadow_owner} && ${shadow_group} == root ]]; then
		echo -e "\n[✓] ${shadow_file} file is secure default (${shadow_owner}:${shadow_group})"
	else
		echo -e "${Yellow}[WARN] Someone messed with the ${shadow_file} file ownership (${shadow_owner})${Reset}"
		echo -e "${Red}[CRITICAL] Immediate attention required!${Reset}"

		if [[ ${FIX_MODE} == true ]]; then

			chown root:root ${shadow_file}
			shadow_owner=$(stat -c "%U" "${shadow_file}")

			echo -e "\n[FIXED] ${shadow_file} file ownership set to default (${shadow_owner})"
		fi
	fi
}
check_shadow_ownership
